###

POST http://localhost:3000/api/libros/
Content-Type: application/json

{
    "titulo": "Don Quijote de la Mancha",
    "autor": "Miguel de Cervantes",
    "anio": "1605"
}

###

GET http://localhost:3000/api/libros/
Content-Type: application/json

###

GET http://localhost:3000/api/libros/libros?search=Rayuela
Content-Type: application/json

### 

DELETE http://localhost:3000/api/libros/1
Content-Type: application/json

###

PATCH HTTP://localhost:3000/api/libros/10
Content-Type: application/json

{
    "autor": "Osvaldeado"
}